language: node_js
node_js:
  - node
  - '6'
os:
  - linux
after_success: npm run coveralls
jobs:
  include:
    - stage: npm release
      node_js: '6'
      deploy:
        provider: npm
        email: reginfo@nativecode.com
        api_key:
          secure: >-
            ROXDl1k0jliIuMZc6wql5PLbcFBVLbq8xwx4Wq12KmZiWBO1URE6f1Vbsw2FuQM0RwZAnepcvDh1G0Ks9G658jQdEwa09M8fO3EoRp5fuKqNU30wxOW5daHVJuRFlXISwbVjQ6i/8HNgj/zKd62ylB87HxeAuBBLa3mZqBrxavRTYYNZy2j/z2O7vJebDkKsGRZ8nK5/8hKQXcBE2t501CK79IsXyCm/WShdPWLf31/fmkq6JNQ3zfLG7y5qXMtwPBsVYW2Oguvc0htbw+sS7AIygWqC8HhW+sCQ0ouhw/lx28+8MiYmMQ94bogoBehShj0DHHItPg33kBYDoM/jNm9mIYMt/IIFdgNNs/zmQ1dgHVfSfSZ4TQdI1xEaYfYaDd7CI39K/24r+xga3BeJ/YYQdx3cJm8uZJFxmeq16zJRnnbYGzoU5l89gExrWdPOVHC5r0YBdYlRXuOFlzX7lEm4+d+MEq9ebD65KPZQconFa34j7HMuVp9xuqzUB5OFG9Hf2dV30IyCZIc5O0aqHR8FJlSx5kkICwL8p2NqxrPYgVfguZ1EFwkBphKdNbqDnwswMY4j3cw5SCXqf9mam0Sj0flwP8lVw+Fhq5Am59tmmGGhdIKucXTwBH2+BVtelSaBBic9Z/c5hyxEaYVYW+iVFDLGneiFV/KvRU0pBb8=
        'on':
          branch: master
        skip_cleanup: true
