export interface SshHost {
  addKeysToAgent: string
  addressFamily: string
  batchMode: string
  bindAddress: string
  canonicalDomains: string
  canonicalizeFallbackLocal: string
  canonicalHostname: string
  canonicalizeMaxDots: string
  canonicalizePermittedCNAMEs: string
  certificateFile: string
  challengeResponseAuthentication: string
  checkHostIP: string
  cipher: string
  ciphers: string
  clearAllForwardings: string
  compression: string
  compressionLevel: string
  connectionAttempts: string
  connectTimeout: string
  controlMaster: string
  controlPath: string
  controlPersist: string
  dynamicForward: string
  enableSSHKeysign: string
  escapeChar: string
  exitOnForwardFailure: string
  fingerprintHash: string
  forwardAgent: string
  forwardX11: string
  forwardX11Timeout: string
  forwardX11Trusted: string
  gatewayPorts: string
  globalKnownHostsFile: string
  SSAPIAuthentication: string
  GSSAPIDelegateCredentials: string
  hashKnownHosts: string
  hostbasedAuthentication: string
  hostbasedKeyTypes: string
  hostKeyAlgorithms: string
  hostKeyAlias: string
  hostName: string
  identitiesOnly: string
  identityAgent: string
  identityFile: string
  ignoreUnknown: string
  include: string
  IPQoS: string
  kbdInteractiveAuthentication: string
  kbdInteractiveDevices: string
  kexAlgorithms: string
  localCommand: string
  localForward: string
  logLevel: string
  MACs: string
  noHostAuthenticationForLocalhost: string
  numberOfPasswordPrompts: string
  passwordAuthentication: string
  permitLocalCommand: string
  PKCS11Provider: string
  port: string
  preferredAuthentications: string
  protocol: string
  proxyCommand: string
  proxyJump: string
  proxyUseFdpass: string
  pubkeyAcceptedKeyTypes: string
  pubkeyAuthentication: string
  rekeyLimit: string
  remoteForward: string
  requestTTY: string
  revokedHostKeys: string
  rhostsRSAAuthentication: string
  RSAAuthentication: string
  sendEnv: string
  serverAliveCountMax: string
  serverAliveInterval: string
  streamLocalBindMask: string
  streamLocalBindUnlink: string
  strictHostKeyChecking: string
  TCPKeepAlive: string
  tunnel: string
  tunnelDevice: string
  updateHostKeys: string
  usePrivilegedPort: string
  user: string
  userKnownHostsFile: string
  verifyHostKeyDNS: string
  versionAddendum: string
  visualHostKey: string
  xAuthLocation: string
}
