language: node_js
node_js:
  - node
  - '6'
os:
  - linux
after_success: npm run coveralls
jobs:
  include:
    - stage: npm release
      node_js: '6'
      deploy:
        provider: npm
        email: reginfo@nativecode.com
        api_key:
          secure: >-
            BFQdH4bEgxRuqo3X6n2RhlO4sK2/WKrYB215qtLayHfab3blsV9P/QEDYks6zVZodW/tAG9czutGcgc0gdFsP3F7KnY9Nh3pbX/S2QYMFa0qbOAMhCeg7QSn7E/Uu1PcH2waknOrGbAGn5Wb5Q84N0pKUUibdc8Z13XFPS+kpG/r129VA9DSi3nJ8NAbJuCOv8F4baBbqBFE5va9e85bJ3xlgGmrxEdBdAGVH0QCezXJGz+A1rtUxHfw57k4iEXQIBEejOvohlVCcR9wsTtFxfAsjuk7hzDY6hzlndISx2tx7+mfCGPnovsdkpKPsX2xAKvmzIao+NztH5Jcyhrp2ditvqnASNv4gIDsCLurVMl3ZQNj6oe5AWkOaHeMwbVObPGJ1iGIsD9tjlQiJnGA2A6wCcEoJtSWQGVV06tFIkEXPk8a/qltU4XGTmBN3lbEk3w8gXs3WiAMMywmLNTjiTEiA4WylyfrU+VSTO/7Dc/TXO5GyBLEd1CqPVD4f4bO4+mCea/tYzvoC3pSuZKpzp6Vh/pAbGeuwdAduykAEmV6GRA0RDGOmWvfBJV3ceDhNHHU2zjnZ68xX56+LsRfxLCPi53U9aLuavj/kUgMxmH/KLzf0cPaab0D1OCDp5o9s+UD0tQH2w+E0RixWJ3wq75qE4FaAMW/zDIxir6IAuw=
        'on':
          branch: master
        skip_cleanup: true
