language: node_js
node_js:
  - 'node'
  - '8'
os: linux
stages:
  - test
  - name: deploy
    if: (branch = "master" OR branch = "master-lts" OR branch = "develop") AND type != pull_request AND tag IS blank
jobs:
  include:
    - stage: deploy
      node_js: '8'
      os: linux
      script:
        - npm run travis-ssh
        - git remote set-url origin git@github.com:nativecode-dev/nofrills.git
        - git checkout $TRAVIS_BRANCH
        - npm run push
after_failure:
  - cat lerna-debug.log
after_success:
  - npm run travis-coveralls
