cache:
  directories:
    - node_modules
  yarn: true
language: node_js
node_js:
  - 'node'
  - '8'
os: linux
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm whoami
  - yarn global add lerna
  - sh ./travis/setup-git.sh
stages:
  - test
  - name: coverage
    if: (branch = "master" OR branch = "develop") AND type != pull_request
  - name: deploy
    if: (branch = "master" OR branch = "develop") AND type != pull_request
jobs:
  include:
    - stage: coverage
      node_js: '8'
      os: linux
      script:
        - yarn run setup-ssh
        - git remote set-url origin git@github.com:nativecode-dev/nofrills.git
        - git checkout $TRAVIS_BRANCH
        - yarn run coveralls
    - stage: deploy
      node_js: '8'
      os: linux
      script:
        - yarn run setup-ssh
        - git remote set-url origin git@github.com:nativecode-dev/nofrills.git
        - git checkout $TRAVIS_BRANCH
        - yarn run release
after_failure:
  - cat lerna-debug.log
