cache: yarn
language: node_js
node_js:
  - node
  - '8'
  - '6'
os:
  - linux
after_success:
  - npm run coveralls
stages:
  - test
  - name: deploy-develop
    if: branch = develop AND type = pull_request
    env:
      - BUILD_TAG=pr-$TRAVIS_PULL_REQUEST_BRANCH-$TRAVIS_PULL_REQUEST
      - BUILD_VERSION=prerelease
  - name: deploy-lts
    if: branch = lts AND type != pull_request
    env:
      - BUILD_TAG=latest
      - BUILD_VERSION=patch
  - name: deploy-master
    if: branch = master AND type != pull_request
    env:
      - BUILD_TAG=next
      - BUILD_VERSION=minor
jobs:
  include:
    - stage: deploy-develop
      script: yarn run build && yarn run push
    - stage: deploy-lts
      script: yarn run build && yarn run push
    - stage: deploy-master
      script: yarn run build && yarn run push
