cache:
  yarn: true
language: node_js
node_js:
  - 'node'
  - '8'
os: linux
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add lerna
stages:
  - test
  - name: deploy
    if: (branch = "master" OR branch = "master-lts" OR branch = "develop") AND type != pull_request AND tag IS blank
jobs:
  include:
    - stage: deploy
      node_js: '8'
      os: linux
      script:
        - yarn run travis-ssh
        - git remote set-url origin git@github.com:nativecode-dev/nofrills.git
        - git checkout $TRAVIS_BRANCH
        - yarn run test
        - yarn run travis-coveralls
        - yarn run push
after_failure:
  - cat lerna-debug.log
