cache: yarn
language: node_js
node_js:
  - node
  - '8'
  - '6'
os:
  - linux
after_success:
  - yarn run coveralls
  - |
    declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)" openssl aes-256-cbc \
      -K $encrypted_XXXXXXXXXXXX_key \
      -iv $encrypted_XXXXXXXXXXXX_iv \
      -in ".travis/github_deploy_key.enc" \
      -out "$SSH_FILE" -d
    chmod 600 "$SSH_FILE" && printf "%s\n" \
           "Host github.com" \
           "  IdentityFile $SSH_FILE" \
           "  LogLevel ERROR" >> ~/.ssh/config
stages:
  - test
  - name: deploy-master
    if: branch = master AND type != pull_request
jobs:
  include:
    - stage: deploy-master
      script: yarn run push
