cache:
  directories:
    - node_modules
  yarn: true
language: node_js
node_js:
  - 'node'
os:
  - linux
  - osx
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:./node_modules/.bin:$PATH"
  - npm config set registry https://registry.npmjs.org/_authToken=$NPM_TOKEN
  - npm whoami
  - yarn global add lerna@2.11.0
  - yarn run setup-git
stages:
  - test
  - name: coverage
    if: branch = "master" OR branch = "develop"
  - name: release
    if: branch = "master" AND type != pull_request
jobs:
  include:
    - stage: coverage
      node_js: '8'
      os: linux
      script:
        - yarn run coveralls
    - stage: release
      node_js: '8'
      os: linux
      script:
        - yarn run setup-ssh
        - git remote set-url origin git@github.com:nativecode-dev/nofrills.git
        - git checkout $TRAVIS_BRANCH
        - yarn run release
after_failure:
  - cat lerna-debug.log
