cache: yarn
language: node_js
node_js:
  - node
os: linux
stages:
  - test
  - name: deploy
    if: branch = master AND type != pull_request
jobs:
  include:
    - stage: deploy
      script: yarn run push
after_failure:
  - cat lerna-debug.log
after_success:
  - yarn run coveralls
before_deploy:
  - yarn run predeploy
before_install:
  - 'curl -o- -L https://yarnpkg.com/install.sh | bash -s'
  - 'export PATH="$HOME/.yarn/bin:$PATH"'
  - 'npm set //registry.npmjs.org/:_authToken "$NPM_TOKEN"'
