cache: yarn
language: node_js
node_js:
  - node
  - '8'
  - '6'
os:
  - linux
after_success:
  - npm run coveralls
stages:
  - test
  - name: deploy-develop
    if: branch = develop AND type = pull_request
  - name: deploy-master
    if: branch = master AND type != pull_request
jobs:
  include:
    - stage: deploy-develop
      script: yarn run build && yarn run push --allow-branch=develop --npm-tag=pr-$TRAVIS_PULL_REQUEST
    - stage: deploy-master
      script: yarn run build && yarn run push --allow-branch=master --npm-tag=latest
