cache: yarn
language: node_js
node_js:
  - node
  - '8'
  - '6'
os:
  - linux
before_deploy:
  - $(npm bin)/set-up-ssh --key "$encrypted_fa989ae4fdf1_key" --iv "$encrypted_fa989ae4fdf1_iv" --path-encrypted-key "nofrills_deploy_key.enc"
stages:
  - test
  - name: deploy
    if: branch = master AND type != pull_request
jobs:
  include:
    - stage: deploy
      script: yarn run push
after_success:
  - yarn run coveralls
