cache: yarn
language: node_js
node_js:
  - node
  - '8'
  - '6'
os:
  - linux
after_success:
  - npm run coveralls
stages:
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: deploy
      script: yarn run build && yarn run push
