cache: yarn
language: node_js
node_js:
  - node
  - '8'
  - '6'
os: linux
stages:
  - test
  - name: deploy
    if: branch = master AND type != pull_request AND tag IS blank
jobs:
  include:
    - stage: deploy
      script:
        - yarn run travis-ssh
        - 'git remote set-url origin git@github.com:nativecode-dev/nofrills.git'
        - git checkout master
        - 'npm set //registry.npmjs.org/:_authToken "$NPM_TOKEN"'
        - yarn run push
after_failure:
  - cat lerna-debug.log
after_success:
  - yarn run travis-coveralls
before_install:
  - 'curl -o- -L https://yarnpkg.com/install.sh | bash -s'
  - 'export PATH="$HOME/.yarn/bin:$PATH"'
