cache: yarn
language: node_js
node_js:
  - node
os: linux
stages:
  - test
  - name: deploy
    if: branch = master AND type != pull_request
jobs:
  include:
    - stage: deploy
      script:
        - yarn run push
after_install:
  - yarn run ssh
  - export RELEASE_BRANCH=release-$TRAVIS_BUILD_NUMBER
  - 'git remote set-url origin git@github.com:nativecode-dev/nofrills.git'
  - git status
  - echo $RELEASE_BRANCH
  - git rebase HEAD master
  - 'npm set //registry.npmjs.org/:_authToken "$NPM_TOKEN"'
after_failure:
  - cat lerna-debug.log
after_success:
  - yarn run coveralls
before_install:
  - 'curl -o- -L https://yarnpkg.com/install.sh | bash -s'
  - 'export PATH="$HOME/.yarn/bin:$PATH"'
