#!/bin/bash

[[ ${CI} ]] && NPM_COMMAND="ci" || NPM_COMMAND="install"
PATH=${PATH}:./node_modules/.bin

if [ ! -d node_modules ]; then
    npm ${NPM_COMMAND}
    npm run bootstrap
fi

./node_modules/.bin/lerna "$@"
