language: node_js
node_js:
  - node
  - '6'
os:
  - linux
after_success: npm run coveralls
jobs:
  include:
    - stage: npm release
      node_js: '6'
      deploy:
        provider: npm
        email: reginfo@nativecode.com
        api_key:
          secure: >-
            EYQZ0fbFKdMwdykl5jq2aTfKUSSFuYkHqn6L/2zGD/RpGea+msHsicYfv87imYoMm+4hpJ2zN0JdAYfI7UEx2VIcRa4wQONPDbpJWjp33QGzs0qUeD9QdWJEjX5eh136I2yo0sytByMSNf0eJVYzQlvmatiLd0DuwcibnAuo6WjTGoVwlB4Q6Tfz3gOVeku38wWMVKsg/sjNzvnihJEWL74+kg9IjYxjWEwm710fSWW5kP2dUEQqlA0KNvsewWCqqWkBbbGPA52Wd7AYXI5C4V50JvRAuSM7wlLkB/HCP1jlI1FxystGtCd+QoLe/csuTRuG0DJTw54GnJMRgSZgwNjAwziMCwdqpDl1bubon8gGVWmrcQZ26Njl5MACLPWGogLa+GKu8wtPuSBpyWnGT9BUD4i0e4lonyKbBpD+r6FSWXSoxyFzMFA+aCPxUa0HP7bwbbOY8s56/FXiLcvVJ7OInxiNGASFY/dloLNhM0RI7NBKMY5CdcEHJHoc0w1bp3ZUjxx6QvKb172dUoyEVSGcRqNJZGu8sXJJMQUDz7nadcCSNMvZzdqVt7RIdSwVm/Muc2Y248JK60EAeBHKqtSVR648GEj9SXFAGYQ+y/JZ47ft/wIy6u7gIq85T2yV8Yp+MN1/QUgIcWWV+XLZ9RLWxpUefieEerzX/LDr4ks=
        'on':
          branch: master
        skip_cleanup: true
