language: node_js

node_js:
  - node
  - '6'

os:
  - linux

after_success: npm run coveralls

jobs:
  include:
    - stage: npm release
      node_js: "6"
      before_deploy: npm run build
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: reginfo@nativecode.com
        api_key:
          secure: k8UOQ4j/oQRNuiiYqH4DwYyU/lqTE0Rai57QIzlmvQVLdKjXsCejCUVtQS/Lu8kO6VzgyTN7EAL5RXROBACM8HNH2JCBmqWItYrtMITt2N2N9gFOaEpz8Ld4hkoaawghV/Nc79pi+XUsm9zKWkPHNwWpNJABGzDuujyDjCN1BWEQ3QNJI1XxYpZzXH22kC6jA6gjVkthebQB/DH4dUEw+8m8DQhV0KCK6zHXJfIRtKw2wMqaKvMIbeTm1H6dJ+g80ssAjFnf7iYvdu2jS5FI3Olz3q+gknihE3VMKadsDJPH8drDD+3Byv0EvX3T207/0rOQGPsyJaXQbva2X/Alv/ieW4D6mKj4jqmCw00pP61JP1xbGSa/IXmut0LUxSxFrwABrqbNg0wN85bl8/FYVx6AM+pT0ncDBH1Gl403bh0sg7Cwa4JgMycH1Z+sjRPYdooamhFQkdvcwDX2Us+RxDh30ngbS8858sQS8reDkl6nRCRLqYlyLA2KpuNHmaq53R/CeECeCg4XebYrQXP8ppUT4M+RpKMMQt+UTM4n+vYyyD6lv2U6wnpqkeZg3dfgjQyEPCyVXI24oyD8j/bg9U5MOlXI2oNIVkeIaDGe7Q3tpCc1fbHKjD6qNOTaC2G3uytS+EMsg19kXumuwatRN8ZZj7ErMzJGLD2+mQ0bXgM=
        on:
          branch: master
        skip_cleanup: true
