language: node_js
node_js:
- node
- '6'
os:
- linux
after_success: npm run coveralls
jobs:
  include:
  - stage: npm release
    node_js: '6'
    before_deploy: npm run build
    script: echo "Deploying to npm ..."
    deploy:
      provider: npm
      email: reginfo@nativecode.com
      api_key:
        secure: T5ghmn4D19qSady9dD7JTyAjOxgkonEhs6nJEawPSNxB7+a70Dews8PYukNTMkC3R5hkpt2keI8Zo2T3TwayiAKiBxB5H7Q5uOJeFrJ3sOwOpQQlt7HNOIlygjikiuZ7aSQxUTFytetNcgkuMGOCFI9bk7Jz0DzNZficPRzi3UbgiyhFxPH5dV+w/CjVf5XYyjd/yCRfRilwdxUvaj5Iv/fzO4tQ1+ockiG8xSnhDPfiDTS/BKZSv5XLlq8FNpPXALYz0szMvda8EFT7NMprPT+82SsX5Ivv4+Sfu/oP3NjHK10GZllqMlWTOICUW5GygL7F6IXuuzSOTCIL3+3AC4y50LmpNHgejQ8Z/QejAbzJideDliJ4vD/+0RdtHhl+arpPXJOAlw5aNIE2llZqZLBHdWE5F0SYIE2AiYZ642LNLEp7iXN+MRzjTwm7y/8sOAiltmpZQhoDeKFT4w+ex2+a1Hu2tByW9BQMlYht8frrsj4cmqLiIXqZfqe+oNIYNUHA4j1MWK5WNPJxGEKfQt1wyNf8FZwosCZkqULzq5CiXNlPO+5l92JaMJd0lbgZcdqOz1GwMls8bTF/iTXmSo40o38bCIKUZe1z1qLPmzhwLkA1dq5duk6F3pl2suQhyQYl37bYRcHE8/VzuHsx39E+aQvSkdUBQH552AME2GU=
      on:
        branch: master
      skip_cleanup: true
